config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :customers
  mount Sidekiq::Web => '/sidekiq'
  root 'main_dashboard#index'
  get 'main_dashboard/index'
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :webhooks, only: [:create]

  resources :products do
    collection do
      get :add
      post :import
    end
  end

  resources :orders do
    collection do
      post :create_payment
      get :success
      get :cancel
    end
  end

  resources :carts, only: [:index] do
    collection do
      post :add
    end
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  include AASM
  has_many :line_items, dependent: :destroy
  has_one :shipping_address, dependent: :destroy
  belongs_to :customer

  scope :with_shipping_address, lambda {
                                  joins(:shipping_address).includes(line_items: :product).select("orders.*, CONCAT(line1,', ',line2,', ',city,', ',state,', ',country) as address").order(created_at: :desc)
                                }

  aasm column: 'status' do
    state :paid, initial: true
    state :in_process, :shipped, :delivered

    event :process do
      transitions from: :paid, to: :in_process
    end

    event :ship do
      transitions from: :in_process, to: :shipped, if: :shipping_address_present?
      after do
        SendShippingEmailJob.perform_later(id)
      end
    end

    event :deliver do
      transitions from: :shipped, to: :delivered
    end

    event :cancel do
      transitions from: %i[paid in_process shipped], to: :cancelled
    end
  end

  def shipping_address_present?
    shipping_address.present?
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @pagy, @orders = pagy(current_customer.orders.with_shipping_address, items: 5)
  end

  def new
    @q = Product.ransack(params[:q])
    products = params[:q].present? ? @q.result(distinct: true) : Product.all
    @pagy, @products = pagy(products, size: [])
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def create_payment
    if session[:cart_products].blank?
      return redirect_to new_order_path,
                         notice: 'Please add at least one product to cart!'
    end

    session = Stripe::Checkout::Session.create({
                                                 customer: current_customer.stripe_customer_id,
                                                 line_items: prepare_line_items_hash,
                                                 mode: 'payment',
                                                 metadata: { customer_id: current_customer.id },
                                                 shipping_address_collection: { allowed_countries: %w[US IN] },
                                                 success_url: "#{ENV['DOMAIN']}/orders/success",
                                                 cancel_url: "#{ENV['DOMAIN']}/orders/cancel"
                                               })
    redirect_to session.url, allow_other_host: true
  end

  def success
    session.delete(:cart_products)
  end

  def cancel; end

  private

  def prepare_line_items_hash
    order_products = session[:cart_products]
    line_items = []
    order_products.each do |order_product|
      product = Product.find_by(id: order_product['product_id'])
      final_quantity = order_product['quantity'].to_i * product.qty
      line_items.push(
        {
          price_data: {
            currency: 'inr',
            product_data: {
              name: product.name,
              metadata: { "product_id": product.id }
            },
            unit_amount: product.price.to_i * 100
          },
          quantity: final_quantity
        }
      )
    end
    line_items
  end
end

app/views/orders/_cart_buttons.html.erb
<% cart_product =  session[:cart_products] ? session[:cart_products].find { |prd| prd["product_id"].to_i == product_id }: nil %>
<% if cart_product %>
  <div class="input-group">
    <button type="button" class="btn btn-outline-secondary" id="minus-btn" data-controller="request" data-action="click->request#sendRequest" data-request-url-value=<%= add_carts_path(status: 'minus', product_id: product_id)%>>-</button>
    <input type="text" class="form-control text-center" value="<%= cart_product["quantity"] %>" id="<%= product_id%>-quantity" readonly />
    <button type="button" class="btn btn-outline-secondary" id="plus-btn" data-controller="request" data-action="click->request#sendRequest" data-request-url-value=<%= add_carts_path(status: 'add', product_id: product_id)%>>+</button>
  </div>
  <button type="button" class="btn btn-danger"  data-controller="request" data-action="click->request#sendRequest" data-request-url-value=<%= add_carts_path(status: 'remove', product_id: product_id) %> >
    <i class="bi bi-trash"></i>
  </button>
<% else %>
  <button type="button" class="btn btn-primary" data-controller="request" data-action="click->request#sendRequest" data-request-url-value=<%= add_carts_path(status: 'add', product_id: product_id)%>>Add to Cart</button>
<% end %>

app/views/orders/_products_data.html.erb
<% products.find_each do |product| %>
<div class="col-md-3">
  <div class="card mb-3">
    <%= image_tag asset_path('test-product'), class: "card-img-top" , alt: 'Product image' %>
      <div class="card-body">
        <h5 class="card-title">
          <%= product.name %>
        </h5>
        <p class="card-text">
          <%= product.description %>
        </p>
        <p class="card-text"><strong>₹<%= product.price %></strong></p>
        <div class="d-flex justify-content-between align-items-center" id="add-to-cart-<%= product.id %>">
          <%= render 'cart_buttons' , product_id: product.id %>
        </div>
      </div>
  </div>
</div>
<% end %>

app/views/orders/cancel.html.erb
<section>
  <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
</section>

<%= link_to "Back to Products", products_path %>

app/views/orders/index.html.erb
<h1>Orders</h1>
<% if @orders.exists? %>
  <%== pagy_bootstrap_nav(@pagy) %>
  <div class="accordion mt-2" id="accordionExample">
    <% @orders.each.with_index(1) do |order, index| %>
      <div class="accordion-item mt-2">
        <h2 class="accordion-header">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#order_<%= order.id %>" aria-expanded="true" aria-controls="order_<%= order.id %>">
            Order ID #<%= order.id %>
          </button>
        </h2>
        <div id="order_<%= order.id %>" class="accordion-collapse collapse <%= index == 1 ? 'show' : '' %>" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <h6>Status: <span class="badge bg-success"><%= order.status %></span></h6>
            <h6>Order Items</h6>
            <ul>
              <% order.line_items.each do |li| %>
              <li><b>Product:</b> <%= li.product.name %> - <b>Quantity:</b> <%= li.quantity %> - <b>Price:</b> ₹<%= li.product.price.to_i %></li>
              <% end %>
            </ul>
            <h6>Shipping Details</h6>
            <p><b>Address:</b> <%= order.address %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h3 class="text-center mt-3">No Orders Found!</h3>
<% end %>

app/views/orders/new.html.erb
<%= search_form_for @q, url: new_order_path, class: 'mt-3', data: { turbo: false } do |f| %>
  <%= f.label :name_or_description_cont %>
  <%= f.search_field :name_or_description_cont %>

  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to "Clear", new_order_path, class: 'btn btn-danger' %>
<% end %>
<div class="row mt-3">
  <% if @products.exists? %>
    <%= button_to "Proceed with Payment" , create_payment_orders_path, class: 'btn btn-primary mb-2' , method: :post, data: { turbo: :false } %>
    <%= turbo_frame_tag :products, class: 'row' do %>
      <%= render 'products_data', products: @products %>
    <% end %>
    <% if @pagy.next.present? %>
      <%= turbo_frame_tag 'pagination', loading: :lazy, src: new_order_path(format: :turbo_stream, page: @pagy.next) %>
    <% end %>
  <% else %>
    <h3>No products found!</h3>
  <% end %>
</div>

app/views/orders/new.turbo_stream.erb
<%= turbo_stream.append :products do %>
  <%= render 'products_data', products: @products %>
<% end %>
<% if @pagy.next.present? %>
  <%= turbo_stream.replace 'pagination' do %>
    <%= turbo_frame_tag 'pagination', loading: :lazy, src: new_order_path(format: :turbo_stream, page: @pagy.next) %>
  <% end %>
<% else %>
  <%= turbo_stream.remove 'pagination' %>
<% end %>

app/views/orders/success.html.erb
<section>
  <p>
    We appreciate your business! If you have any questions, please email
    <a href="mailto:orders@example.com">orders@example.com</a>.
  </p>
</section>

<%= link_to "Back to Products", products_path %>