config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :customers
  mount Sidekiq::Web => '/sidekiq'
  root 'main_dashboard#index'
  get 'main_dashboard/index'
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :webhooks, only: [:create]

  resources :products do
    collection do
      get :add
      post :import
    end
  end

  resources :orders do
    collection do
      post :create_payment
      get :success
      get :cancel
    end
  end

  resources :carts, only: [:index] do
    collection do
      post :add
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: false, greater_than_or_equal_to: 0 }
  validates :description, presence: true
  validates :qty, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at description id id_value name price qty updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @pagy, @products = pagy(Product.all)
  end

  def add; end

  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  def import
    return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
    return redirect_to request.referer, notice: 'Only CSV files allowed' unless params[:file].content_type == 'text/csv'

    CsvImportService.call(params[:file])

    redirect_to request.referer, notice: 'Import started..! Products will imported soon!'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :description, :qty)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cart_total_products
    session[:cart_products] ? session[:cart_products].map { |a| a['quantity'] }.sum : 0
  end

  def cart_product_quantity(prd_id)
    session[:cart_products].find { |product| product['product_id'].to_i == prd_id }['quantity'].to_i
  end
end

app/views/products/_form.html.erb
<%= form_with model: @product, data: { turbo: false } do |form| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Enter Name' %>
  </div>
  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control', placeholder: 'Enter Price' %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', placeholder: 'Enter Description' %>
  </div>
  <div class="form-group">
    <%= form.label :qty %>
    <%= form.number_field :qty, class: 'form-control', placeholder: 'Enter Quantity' %>
  </div>
  <%= form.submit "Create Product", class: 'btn btn-primary mt-2' %>
<% end %>

app/views/products/add.html.erb
<h1>Import Products</h1>
<%= form_tag import_products_path, method: :post, multipart: true, data: { turbo: false } do %>
  <%= file_field_tag :file, accept: ".csv" %>
  <%= link_to "/sample-products.csv",target: "_blank", class: 'btn btn-info' do %>Download Sample File<% end %>
  <%= submit_tag '⚙️ Import', class: 'btn btn-warning' %>
<% end %>

<%= link_to "Back to Products", products_path, class: 'btn btn-secondary mt-3' %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>
<% if @products.exists? %>
  <%== pagy_bootstrap_nav(@pagy) %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Qty</th>
        <th colspan="4" class="text-center">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td>₹<%= product.price.to_i %></td>
          <td><%= product.description %></td>
          <td><%= product.qty %></td>
          <td>
            <%= link_to product_path(product), class: "btn btn-primary btn-sm" do %>
              <i class="bi bi-eye-fill"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_product_path(product), class: "btn btn-secondary btn-sm" do %>
              <i class="bi bi-pencil"></i>
            <% end %>
          </td>
          <td>
            <%= button_to product, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' do %>
              <i class="bi bi-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>
<% else %>
  <h3>No Products Found!</h3>
<% end %>

<%= link_to 'New Product', new_product_path, class: 'btn btn-primary mt-2' %>
<%= link_to 'Import Products', add_products_path, class: 'btn btn-primary mt-2' %>

app/views/products/new.html.erb
<h1>New Products</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>Product Details</h1>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.qty %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>