config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :customers
  mount Sidekiq::Web => '/sidekiq'
  root 'main_dashboard#index'
  get 'main_dashboard/index'
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :webhooks, only: [:create]

  resources :products do
    collection do
      get :add
      post :import
    end
  end

  resources :orders do
    collection do
      post :create_payment
      get :success
      get :cancel
    end
  end

  resources :carts, only: [:index] do
    collection do
      post :add
    end
  end
end

app/views/layouts/_cart.html.erb
<%= link_to carts_path, class: "btn btn-primary position-relative" do %>
  Cart
  <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
    <%= cart_total_products %>
    <span class="visually-hidden">Cart Items</span>
  </span>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if notice %>
    <div class="alert alert-success alert-dismissible fade show" role="alert" data-controller="removals">
      <strong><%= notice %></strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger alert-dismissible fade show m-1" role="alert" data-controller="removals">
      <strong><%= alert %></strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Home", main_dashboard_index_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if customer_signed_in? %>
          <li class="nav-item">
            <%= link_to "Products", products_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Orders", orders_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "New Order", new_order_path, class: 'nav-link' %>
          </li>
        <% end %>
        <% unless customer_signed_in? %>
          <li class="nav-item">
            <%= link_to "Login", new_customer_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Signup", new_customer_registration_path, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_customer_session_path, data: { turbo_method: :delete }, class: 'nav-link btn btn-danger' %>
          </li>
        <% end %>
      </ul>
      <div id="cart-button"><%= render 'layouts/cart' %></div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DockerExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track" => "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>